### ISSUE TITLE
End of video error

### ISSUE THREAD

**Issue by defrag-bambino** [klintan/ros2_video_streamer#5]
Hi,

I was using your node to publish a very short video and noticed that once the video ends, the node crashes while throwing an error. This is due to the opencv video capture not being able to read the next frame (as the video is over) and thus the image variable being 'None'.
I fixed this in my fork [here](https://github.com/defrag-bambino/ros2_video_streamer_fork). I opened a PR [here](https://github.com/klintan/ros2_video_streamer/pull/4).
While at it, I also implemented the '--loop' feature, which allows one to not close the node after the end of the video, but loop it.

Thanks

**Comment by klintan** [comment]
Thanks for fixing this, merged the PR so closing this.
