### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vkuehn** [klintan/ros2_video_streamer#7]
can you kindly add some documentation how to actually prepare a video for streaming ?

would it be possible to directly stream(or record) some simple webcam ?

**Comment by klintan** [comment]
Hello!

Could you elaborate on what kind of documentation you expect?

To run it this should be the way: `ros2 run camera_simulator camera_simulator --type video --path <my-video-path> --loop` ( it might have changed in later versions of ros2, feel free to ping me if that is the case) 

Further in terms of what video-files that work, if it's mp4 or mpeg it should work.

If you want to stream live from a webcam this is not the library to use, this is for video files on your harddrive. For webcam streaming in Ros2 I have this library https://github.com/klintan/ros2_usb_camera but there is also a bunch of others if you want alternatives.

**Comment by klintan** [comment]
I'll close this one if you don't have any further questions. Feel free to create a new issue including more details if necessary.

**Comment by vkuehn** [comment]
@klintan oh sorry for the late response. I'll try out your suggested  link as I am searching for an easy way of plug and play usb cameras.

Thanks
